# -------------------------------------------------------------
# PostgreSQL FOR AIRFLOW
# -------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres-airflow
  namespace: harshith
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-airflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-airflow
  namespace: harshith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-airflow
  template:
    metadata:
      labels:
        app: postgres-airflow
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
            - name: POSTGRES_DB
              value: airflow
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata-airflow
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata-airflow
          emptyDir: {}

---
# -------------------------------------------------------------
# PostgreSQL FOR MLFLOW
# -------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres-mlflow
  namespace: harshith
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-mlflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-mlflow
  namespace: harshith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-mlflow
  template:
    metadata:
      labels:
        app: postgres-mlflow
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              value: mlflow
            - name: POSTGRES_PASSWORD
              value: mlflow
            - name: POSTGRES_DB
              value: mlflow
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata-mlflow
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata-mlflow
          emptyDir: {}