apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: harshith
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: harshith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v2.9.2
          command: ["mlflow", "server"]
          args:
            - "--host=0.0.0.0"
            - "--port=5000"
            - "--backend-store-uri=sqlite:///mlflow.db"
            - "--default-artifact-root=s3://mlflow-artifacts"
            - "--gunicorn-opts=--timeout=300"
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_PORT
              value: "5000"
            - name: MLFLOW_HOST
              value: "0.0.0.0"
            # MinIO S3 configuration
            - name: AWS_ACCESS_KEY_ID
              value: "minio"
            - name: AWS_SECRET_ACCESS_KEY
              value: "minio123"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio.harshith.svc.cluster.local:9000"
            - name: AWS_REGION
              value: "us-east-1"
          volumeMounts:
            - name: mlflowstore
              mountPath: /mlflow
      volumes:
        - name: mlflowstore
          emptyDir: {}