apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: harshith
spec:
  selector:
    app: frontend
  ports:
    - port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: harshith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: my-frontend:latest
          ports:
            - containerPort: 8081
          env:
            - name: PREDICT_URL
              value: http://bento-svc.harshith.svc.cluster.local:3000/predict